apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-deployment
  labels:
    app: resume
spec:
  replicas: 3
  selector:
    matchLabels:
      app: resume
  template:
    metadata:
      labels:
        app: resume
    spec:
      nodeSelector:
        nodepool: resume
      containers:
      - name: resume
        image: kayitesimarieange3h/resume-update:10
        ports:
        - containerPort: 5001
      - name: nginx-proxy   #sidecar container is for a help container
        image: nginx:latest
        ports:
        - containerPort: 8080
      - name: nginx-config
        image: httpd
        ports:
        - containerPort: 8082
---    
apiVersion: v1
kind: Service
metadata:
  name: resume-service
  labels:
    app: resume
spec:
  type: LoadBalancer
  selector:
    app: resume
  ports:
    - name: http
      port: 80
      targetPort: 5001